%% Hellish Quart 対人戦時の画面遷移図
stateDiagram-v2
    m1: トップメニュー
    m2: 対戦メニュー
    s2: 装備品選択
    s3: 相討ち時ルール選択
    s4: キャラクター選択
    s6: アリーナ選択
    L1: ロード画面1
    L2: ロード画面2
    L3: 剣盾画面
    b1: 対戦画面
    b2: フラッグ獲得/相討ち
    b3: 決着（"Left/Right win!" / "Draw!"）
    b4: Rematch画面
    p1: ポーズメニュー
    f1: Free Camera画面

    [*] --> m1
    m1 --> m2 : 対戦メニュー選択
    m2 --> m1 : キャンセル
    m2 --> s2 : vs.player選択
    s2 --> s3
    s2 --> m1 : キャンセル
    s3 --> L1 : 暗転
    L1 --> s4 : 暗転
    s3 --> m1 : キャンセル
    s4 --> s6 : キャラクタ決定：暗転
    s4 --> m1 : キャンセル
    s4 --> s4 : RT長押し：暗転
    s6 --> L1 : キャンセル：暗転
    s6 --> L2 : 暗転
    L2 --> L3
    L3 --> b1
    b1 --> p1
    p1 --> b1 : continue
    p1 --> m1 : main menu：暗転
    b1 --> f1
    p1 --> f1 : Free Camera
    f1 --> b1
    b1 --> b2
    b2 --> b3 : 試合終了
    b2 --> L3 : 試合継続
    b3 --> L1 : 無操作
    b3 --> b4 : Rematch選択
    b4 --> L3
