stateDiagram-v2
s1: キャラクター選択画面
s3: 対戦画面：試合成立前
s4: 対戦画面：試合成立後
s5: （※）試合終了処理

s1 --> s3
s3 --> s1: 試合成立前に中止
s3 --> s4
s4 --> s1: 試合成立後中止または決着
s4 --> s3: 決着後リマッチ

p11: 試合成立フラグ判定
p12: 試合終了処理（※）
p15: 試合成立フラグ下ろす
p16: 「フレーム番号_キャラ決定」保存
p17: キャラ選択画面フラグ立てる
p18: 残１フラグ下ろす

state s1 {
  p11 --> p12: True
  p11 --> p16: False
  p12 --> p15
  p15 --> p16
  p16 --> p17
  p17 --> p18
}

p31: キャラ選択画面フラグ・試合成立フラグ判定
p32: 試合終了処理（※）
p33: 「フレーム番号_キャラ決定」から「使用キャラ」を取得
p34: フラッグ最大数を取得
p35: 3秒前のフレーム番号を「試合開始時間」として保存
p36: 試合成立フラグ下ろす
p37: キャラ選択画面フラグ下ろす
p38: 残１フラグ取得

state s3 {
  p31 --> [*]: どちらも False
  p31 --> p32: 試合成立フラグ True
  p32 --> p35
  p31 --> p33: キャラ選択画面フラグ True
  p33 --> p34
  p34 --> p35
  p35 --> p36
  p36 --> p37
  p37 --> p38
  p38 --> [*]
}

p41: 「フレーム番号_試合終了時」保存
p42: 試合成立フラグ立てる
p43: 残１フラグ取得

state s4 {
  p41 --> p42
  p42 --> p43
}

p51: 「フレーム番号_試合終了時」から「獲得フラッグ数」をカウント
p52: 獲得フラッグ数から試合決着/中止を判定
p53: 「試合開始時刻」「使用キャラ」「獲得フラッグ数」から試合情報を記録

state s5 {
  p51 --> p52
  p52 --> p53: 試合決着
  p52 --> [*]: 試合中止
  p53 --> [*]
}
