stateDiagram-v2
s1: キャラクター選択画面
s2: 対戦画面：試合成立前
s3: 対戦画面：試合成立後
s5: （※）試合終了処理

s1 --> s2
s2 --> s1: 試合成立前に中止
s2 --> s3
s3 --> s1: 試合成立後中止または決着
s3 --> s2: 決着後リマッチ

p11: 「フレーム番号_キャラ決定」保存
p12: 試合進行状況ステータスを「キャラ選択画面」にする

state s1 {
  p11 --> p12
}

p21: （直前の）試合進行状況ステータスを判定
p22: 「フレーム番号_キャラ決定」から「使用キャラ」を取得
p23: フラッグ最大数を取得
p24: 3秒前のフレーム番号を「試合開始時間」として保存
p25: 試合進行状況ステータスを「試合開始後」にする
p26: 残り１フラッグかを判定
p27: 試合進行状況ステータスを「残り１フラッグ」にする

state s2 {
  p21 --> [*]: キャラ選択画面・試合終了後ではない
  p21 --> p22: キャラ選択画面＝新規試合
  p22 --> p23
  p21 --> p24: 試合終了後＝リマッチ
  p23 --> p24
  p24 --> p25
  p25 --> p26
  p26 --> p27: True
  p26 --> [*]: False
  p27 --> [*]
}

p31: （直前の）試合進行状況ステータスを判定
p32: 残り１フラッグかを判定
p33: 試合進行状況ステータスを「残り１フラッグ」にする
p34: （現在の）試合進行状況ステータスを判定
p35: 試合終了かを判定
p36: 試合終了処理（※）
p37: 試合進行状況ステータスを「試合終了後」にする

state s3 {
  p31 --> p32: 残り１フラッグより前
  p32 --> p33: 残り１フラッグ
  p33 --> p34
  p32 --> p34: 残り１フラッグでない
  p31 --> p34: 残り１フラッグ以降
  p34 --> p35: 残り１フラッグ
  p35 --> p36: 試合終了
  p36 --> p37
  p37 --> [*]
  p35 --> [*]: 試合終了ではない
  p34 --> [*]: 残り１フラッグでない
}

p51: 両者の獲得フラッグ数をカウント
p52: 獲得フラッグ数が最大フラッグ数に達しているか
p53: 試合番号をカウントアップ
p54: 「試合開始時間」「試合番号」「両キャラクタ名」「両者獲得フラッグ数」を元にタイムスタンプを記録

state s5 {
  p51 --> p52
  p52 --> [*]: 達していない：試合中止
  p52 --> p53: 達している：試合成立
  p53 --> p54
  p54 --> [*]
}
