stateDiagram-v2
s1: キャラクター選択画面
s2: アリーナ選択画面
s3: 対戦画面：試合成立前
s4: 対戦画面：試合成立後

s1 --> s2
s2 --> s3
s2 --> s1: キャンセル
s3 --> s1: 試合成立前に中止
s3 --> s4
s4 --> s1: 試合成立後中止または決着
s4 --> s3: 決着後リマッチ

p11: 試合成立フラグ判定
p12: 「フレーム番号_試合終了時」から「獲得フラッグ数」をカウント
p13: 獲得フラッグ数から試合決着/中止を判定
p14: 「試合開始時刻」「使用キャラ」「獲得フラッグ数」から試合情報を記録
p15: 試合成立フラグ下ろす
p16: 「フレーム番号_キャラ決定」保存<br>キャラ選択フラグ立てる

state s1 {
  p11 --> p12: 1
  p11 --> p16: 0
  p12 --> p13
  p13 --> p14: 決着
  p13 --> p15: 中止
  p14 --> p15
  p15 --> p16
}

p31: キャラ選択フラグ判定
p32: 3秒前のフレーム番号を「試合開始時間」として保存
p33: 「フレーム番号_キャラ決定」から「使用キャラ」を取得
p34: キャラ選択フラグ下ろす

state s3 {
  p31 --> p32: 1
  p31 --> [*]: 0
  p32 --> p33
  p33 --> p34
  p34 --> [*]
}

p41: 「フレーム番号_試合終了時」保存<br>試合成立フラグ立てる

state s4 {
  p41
}
